### ISSUE TITLE
mario

### ISSUE THREAD

**Issue by bigfinfrank** [AlekEagle/discord-rpc#2]
add pictures of mario

https://cdn.vox-cdn.com/thumbor/Yt1avchDkHqEqJuhYZ3YjKF3kFc=/0x0:1700x960/1200x675/filters:focal(714x344:986x616)/cdn.vox-cdn.com/uploads/chorus_image/image/57514059/mario.0.jpg

**Comment by AlekEagle** [comment]
use your own app
